In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
arr = np.array(l)

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr.max()

np.int64(9)

In [7]:
arr.min()

np.int64(1)

In [8]:
arr.sum()

np.int64(45)

In [9]:
arr.mean()

np.float64(5.0)

In [10]:
arr.std()

np.float64(2.581988897471611)

In [11]:
arr.argmax()

np.int64(8)

In [12]:
arr.argmin()

np.int64(0)

In [13]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [14]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr = np.arange(11,19)
arr

array([11, 12, 13, 14, 15, 16, 17, 18])

In [17]:
arr1 = np.arange(1,31).reshape(6,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr1[0]

array([1, 2, 3, 4, 5])

In [19]:
arr1[5,1]

np.int64(27)

In [20]:
arr1[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [21]:
arr2 = np.arange(10,25)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
bool_index =  arr2%2 ==0
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [23]:
arr2 = arr2[bool_index]
arr2

array([10, 12, 14, 16, 18, 20, 22, 24])

In [24]:
arr2

array([10, 12, 14, 16, 18, 20, 22, 24])

In [25]:
arr2

array([10, 12, 14, 16, 18, 20, 22, 24])

In [26]:
arr3 = np.arange(10,26)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [27]:
bool_idx = arr3%2!=0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True])

In [28]:
arr3 = arr3[bool_idx]
arr3

array([11, 13, 15, 17, 19, 21, 23, 25])

In [29]:
arr3

array([11, 13, 15, 17, 19, 21, 23, 25])

In [30]:
arr2

array([10, 12, 14, 16, 18, 20, 22, 24])

In [31]:
arr3

array([11, 13, 15, 17, 19, 21, 23, 25])

In [32]:
arr4 = arr2+arr3

In [33]:
arr4

array([21, 25, 29, 33, 37, 41, 45, 49])

In [34]:
arr4+=10

In [35]:
arr4

array([31, 35, 39, 43, 47, 51, 55, 59])

In [36]:
arr5 = arr4[:4]
arr5

array([31, 35, 39, 43])

In [37]:
arr6 = arr5
arr6 +=20
arr6

array([51, 55, 59, 63])

In [38]:
arr5

array([51, 55, 59, 63])

In [39]:
arr7 = arr6.copy()
arr7+=10
arr6

array([51, 55, 59, 63])

In [40]:
arr7

array([61, 65, 69, 73])

In [41]:
arr8 = np.array([[1,2,3],[4,5,6]])
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr9 = np.array([[7,8,9],[10,11,12]])
arr9

array([[ 7,  8,  9],
       [10, 11, 12]])

In [43]:
import numpy as np

In [44]:
print(np.max)

<function max at 0x000002614DF13100>
