1st Problem valide Sudoku

In [105]:
import numpy as np

In [90]:
a,b = map(int,input().split())

 3 3


In [91]:
if(a == b):
    print(f"OK! now input the values of a matrix {a} X {a}")
else:
    print("It can't be a sudoku!")

OK! now input the values of a matrix 3 X 3


In [93]:
matrix = np.array([list(map(int, input().split())) for _ in range(b)])

 1 2 3
 4 5 6
 7 8 9


In [94]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
s =np.array([
    [3,9,1,2,8,6,5,7,4],
    [4,8,7,3,5,9,1,2,6],
    [6,5,2,7,1,4,8,3,9],
    [8,7,5,4,3,1,6,9,2],
    [2,1,3,9,6,7,4,8,5],
    [9,6,4,5,2,8,7,1,3],
    [1,4,9,6,7,3,2,5,8],
    [5,3,8,1,4,2,9,6,7],
    [7,2,6,8,9,5,3,4,1],
])

In [113]:
flag = True

In [114]:
r = np.sum(s,1)
r

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [115]:
c = np.sum(s,0)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [116]:
for i in r:
    if(i!=45):
        print("This is not sudoku!")
        break
else: 
    print("This is a sudoku till now!")
    flag = False

This is a sudoku till now!


In [117]:
if(flag):
    print("Do not need to check column sum!")
else:
    for i in c:
        if(i!=45):
            print("This is not sudoku!")
            break 
    else:
        print("This is a sudoku till now!")

This is a sudoku till now!


In [120]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[3 9 1]
 [4 8 7]
 [6 5 2]]
[[2 8 6]
 [3 5 9]
 [7 1 4]]
[[5 7 4]
 [1 2 6]
 [8 3 9]]
[[8 7 5]
 [2 1 3]
 [9 6 4]]
[[4 3 1]
 [9 6 7]
 [5 2 8]]
[[6 9 2]
 [4 8 5]
 [7 1 3]]
[[1 4 9]
 [5 3 8]
 [7 2 6]]
[[6 7 3]
 [1 4 2]
 [8 9 5]]
[[2 5 8]
 [9 6 7]
 [3 4 1]]


2nd Example

In [128]:
#Data is age, math marks, science marks
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [129]:
#Show the shape:
data.shape

(5, 3)

In [134]:
#Find the average age of the student:
age = data[0:,0:1]
age

array([[18],
       [19],
       [17],
       [18],
       [20]])

In [138]:
np.mean(age)

np.float64(18.4)

In [142]:
#Extract math marks of all students
MathMarks = data[ : ,1]
MathMarks

array([85, 92, 76, 65, 90])

In [143]:
#Findthe highest Sciencee Marks:
np.max(data[:,2])

np.int64(95)

In [144]:
#Calculate the avg marks of every students
for i in range(1,3,1):
    for j in range(1,3,1):
        avg = (data[i]+data[j])/2
    print(avg)

[18.  84.  91.5]
[17. 76. 95.]
